// Code generated by protoc-gen-go. DO NOT EDIT.
// source: auth.proto

package model

import (
	fmt "fmt"
	simplcrypto "github.com/cohix/simplcrypto"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type AuthRequest struct {
	TokenSignature       *simplcrypto.Signature          `protobuf:"bytes,1,opt,name=TokenSignature,proto3" json:"TokenSignature,omitempty"`
	PubKey               *simplcrypto.SerializablePubKey `protobuf:"bytes,2,opt,name=PubKey,proto3" json:"PubKey,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                        `json:"-"`
	XXX_unrecognized     []byte                          `json:"-"`
	XXX_sizecache        int32                           `json:"-"`
}

func (m *AuthRequest) Reset()         { *m = AuthRequest{} }
func (m *AuthRequest) String() string { return proto.CompactTextString(m) }
func (*AuthRequest) ProtoMessage()    {}
func (*AuthRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{0}
}

func (m *AuthRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthRequest.Unmarshal(m, b)
}
func (m *AuthRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthRequest.Marshal(b, m, deterministic)
}
func (m *AuthRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthRequest.Merge(m, src)
}
func (m *AuthRequest) XXX_Size() int {
	return xxx_messageInfo_AuthRequest.Size(m)
}
func (m *AuthRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AuthRequest proto.InternalMessageInfo

func (m *AuthRequest) GetTokenSignature() *simplcrypto.Signature {
	if m != nil {
		return m.TokenSignature
	}
	return nil
}

func (m *AuthRequest) GetPubKey() *simplcrypto.SerializablePubKey {
	if m != nil {
		return m.PubKey
	}
	return nil
}

type AuthResponse struct {
	EncSessionKey        *simplcrypto.Message `protobuf:"bytes,1,opt,name=EncSessionKey,proto3" json:"EncSessionKey,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *AuthResponse) Reset()         { *m = AuthResponse{} }
func (m *AuthResponse) String() string { return proto.CompactTextString(m) }
func (*AuthResponse) ProtoMessage()    {}
func (*AuthResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{1}
}

func (m *AuthResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthResponse.Unmarshal(m, b)
}
func (m *AuthResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthResponse.Marshal(b, m, deterministic)
}
func (m *AuthResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthResponse.Merge(m, src)
}
func (m *AuthResponse) XXX_Size() int {
	return xxx_messageInfo_AuthResponse.Size(m)
}
func (m *AuthResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AuthResponse proto.InternalMessageInfo

func (m *AuthResponse) GetEncSessionKey() *simplcrypto.Message {
	if m != nil {
		return m.EncSessionKey
	}
	return nil
}

func init() {
	proto.RegisterType((*AuthRequest)(nil), "goott.server.model.AuthRequest")
	proto.RegisterType((*AuthResponse)(nil), "goott.server.model.AuthResponse")
}

func init() { proto.RegisterFile("auth.proto", fileDescriptor_8bbd6f3875b0e874) }

var fileDescriptor_8bbd6f3875b0e874 = []byte{
	// 246 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x90, 0x31, 0x4b, 0x04, 0x31,
	0x10, 0x46, 0x59, 0x8b, 0x2b, 0x72, 0x6a, 0x11, 0x10, 0x0f, 0x1b, 0x8f, 0x13, 0xc1, 0xc6, 0x04,
	0xb4, 0x11, 0x2c, 0x44, 0xc1, 0xea, 0x10, 0x64, 0xcf, 0xca, 0x2e, 0xbb, 0x0e, 0xbb, 0xe1, 0x36,
	0x99, 0x98, 0x99, 0x88, 0xeb, 0x2f, 0xf0, 0x67, 0x8b, 0x89, 0x08, 0x2b, 0xd6, 0x79, 0xdf, 0x63,
	0xf2, 0x84, 0x30, 0x89, 0x7b, 0x15, 0x22, 0x32, 0x4a, 0xd9, 0x21, 0x32, 0x2b, 0x82, 0xf8, 0x06,
	0x51, 0x39, 0x7c, 0x81, 0xe1, 0xe8, 0x98, 0xac, 0x0b, 0x43, 0x1b, 0xc7, 0xc0, 0xa8, 0x33, 0xa6,
	0x1d, 0x10, 0x99, 0x0e, 0xca, 0xe8, 0x3f, 0x60, 0x0b, 0x63, 0x30, 0x36, 0x16, 0x60, 0xf5, 0x59,
	0x89, 0xf9, 0x6d, 0xe2, 0xbe, 0x86, 0xd7, 0x04, 0xc4, 0xf2, 0x46, 0xec, 0x3f, 0xe1, 0x16, 0xfc,
	0xc6, 0x76, 0xde, 0x70, 0x8a, 0xb0, 0xa8, 0x96, 0xd5, 0xd9, 0xfc, 0xe2, 0x50, 0x65, 0x93, 0x2a,
	0x2a, 0xf5, 0xfb, 0x5c, 0xff, 0xc1, 0xe5, 0x95, 0x98, 0x3d, 0xa6, 0x66, 0x0d, 0xe3, 0x62, 0x27,
	0x0f, 0x97, 0xd3, 0x21, 0x41, 0xb4, 0x66, 0xb0, 0x1f, 0xa6, 0x19, 0xa0, 0x70, 0xf5, 0x0f, 0xbf,
	0x5a, 0x8b, 0xdd, 0x72, 0x09, 0x05, 0xf4, 0x04, 0xf2, 0x5a, 0xec, 0xdd, 0xfb, 0x76, 0x03, 0x44,
	0x16, 0xfd, 0xb7, 0xb0, 0x5c, 0x72, 0x30, 0x15, 0x3e, 0x94, 0xff, 0xd6, 0x53, 0xf6, 0xee, 0xf4,
	0xf9, 0xa4, 0xb3, 0xdc, 0xa7, 0x46, 0xb5, 0xe8, 0x74, 0x8b, 0xbd, 0x7d, 0xd7, 0x39, 0xe0, 0x79,
	0x09, 0xa8, 0x73, 0xc0, 0x66, 0x96, 0x2b, 0x5c, 0x7e, 0x05, 0x00, 0x00, 0xff, 0xff, 0x62, 0x69,
	0x45, 0xeb, 0x69, 0x01, 0x00, 0x00,
}
