// Code generated by protoc-gen-go. DO NOT EDIT.
// source: service.proto

package service

import (
	fmt "fmt"
	model "github.com/cohix/goott-server/model"
	proto "github.com/golang/protobuf/proto"
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

func init() { proto.RegisterFile("service.proto", fileDescriptor_a0b84a42fa06f626) }

var fileDescriptor_a0b84a42fa06f626 = []byte{
	// 148 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2d, 0x4e, 0x2d, 0x2a,
	0xcb, 0x4c, 0x4e, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x12, 0x49, 0xcf, 0xcf, 0x2f, 0x29,
	0xd1, 0x03, 0x09, 0xa6, 0x16, 0xe9, 0x41, 0xe5, 0xa4, 0xc4, 0x72, 0xf3, 0x53, 0x52, 0x73, 0xf4,
	0xc1, 0x4a, 0xf4, 0x13, 0x4b, 0x4b, 0x32, 0x20, 0xaa, 0x8d, 0x82, 0xb8, 0x58, 0xdd, 0x41, 0xea,
	0x85, 0x3c, 0xb9, 0x58, 0x1c, 0x4b, 0x4b, 0x32, 0x84, 0xe4, 0xf5, 0x50, 0xf4, 0x83, 0xb5, 0xe9,
	0x81, 0x64, 0x82, 0x52, 0x0b, 0x4b, 0x53, 0x8b, 0x4b, 0xa4, 0x14, 0x70, 0x2b, 0x28, 0x2e, 0xc8,
	0xcf, 0x2b, 0x4e, 0x75, 0x52, 0x8f, 0x52, 0x4d, 0xcf, 0x2c, 0xc9, 0x28, 0x4d, 0xd2, 0x4b, 0xce,
	0xcf, 0xd5, 0x4f, 0xce, 0xcf, 0xc8, 0xac, 0xd0, 0x07, 0xeb, 0xd1, 0x85, 0xe8, 0xd1, 0x87, 0x3a,
	0x2a, 0x89, 0x0d, 0xec, 0x06, 0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0xa5, 0x5c, 0x08, 0xe0,
	0xc2, 0x00, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// GoottClient is the client API for Goott service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GoottClient interface {
	Auth(ctx context.Context, in *model.AuthRequest, opts ...grpc.CallOption) (*model.AuthResponse, error)
}

type goottClient struct {
	cc *grpc.ClientConn
}

func NewGoottClient(cc *grpc.ClientConn) GoottClient {
	return &goottClient{cc}
}

func (c *goottClient) Auth(ctx context.Context, in *model.AuthRequest, opts ...grpc.CallOption) (*model.AuthResponse, error) {
	out := new(model.AuthResponse)
	err := c.cc.Invoke(ctx, "/goott.server.service.Goott/Auth", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GoottServer is the server API for Goott service.
type GoottServer interface {
	Auth(context.Context, *model.AuthRequest) (*model.AuthResponse, error)
}

func RegisterGoottServer(s *grpc.Server, srv GoottServer) {
	s.RegisterService(&_Goott_serviceDesc, srv)
}

func _Goott_Auth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(model.AuthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoottServer).Auth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/goott.server.service.Goott/Auth",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoottServer).Auth(ctx, req.(*model.AuthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Goott_serviceDesc = grpc.ServiceDesc{
	ServiceName: "goott.server.service.Goott",
	HandlerType: (*GoottServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Auth",
			Handler:    _Goott_Auth_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service.proto",
}
